export function identifier(char, nextChar = '', prevChar = '') {
	if (char === '#') return 'heading'
	if (char === '-' && nextChar === ' ') return 'bullet'
	if (char === '*' && nextChar === ' ') return 'bullet'
	if (char === '+' && nextChar === ' ') return 'bullet'
	if (/\d/.test(char)) return 'number'
	if (char === '`') return 'code'
	if (char === '~') return 'code'
	if (char === '>' && nextChar === ' ') return 'blockquote'
	if (char === '[') return 'link_start'
	if (char === '!') return 'image'
	if (char === '*' || char === '_') return 'emphasis'
	if (char === '|') return 'table'
	if (char === '-' || char === '*' || char === '_') return 'hr'
	if (char === '=' || char === '-') return 'setext_header'
	if (char === ':' && nextChar === ' ') return 'definition'
	if (char === '$') return 'math'
	if (char === '[' && nextChar === '^') return 'footnote'
	return 'text'
}
